name: Apple

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-pods:
    name: Lint pod
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-apple

      - name: pod lib lint
        run: pod lib lint --verbose --include-podspecs=**/*.podspec
