name: Swift

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Debug
        run: swift build -c debug

      - name: Build Release
        run: swift build -c release
